name: '[CI] E2E Test'
description: 'Run e2e tests against an EKS cluster'
inputs:
  image:
    description: 'NMA container image to deploy'
    required: true
  test_filter:
    description: 'Test filter pattern (e.g., Test/DaemonSetReady)'
    required: false
    default: ''
  timeout:
    description: 'Test timeout'
    required: false
    default: '30m'
outputs:
  test_results:
    description: 'JSON-formatted test results'
    value: ${{ steps.parse-results.outputs.results }}
  passed:
    description: 'Number of tests passed'
    value: ${{ steps.parse-results.outputs.passed }}
  failed:
    description: 'Number of tests failed'
    value: ${{ steps.parse-results.outputs.failed }}
  skipped:
    description: 'Number of tests skipped'
    value: ${{ steps.parse-results.outputs.skipped }}
runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache-dependency-path: e2e/go.sum

    - name: Generate manifests
      shell: bash
      run: make update-e2e-manifests

    - name: Run e2e tests
      id: run-tests
      shell: bash
      run: |
        set +e
        
        # Build test command
        TEST_CMD="go test -v -tags=e2e -timeout ${{ inputs.timeout }} ./e2e/..."
        TEST_CMD="$TEST_CMD --install=true --image=${{ inputs.image }}"
        
        # Add filter if provided
        if [ -n "${{ inputs.test_filter }}" ]; then
          TEST_CMD="$TEST_CMD -run '${{ inputs.test_filter }}'"
        fi
        
        echo "Running: $TEST_CMD"
        
        # Run tests and capture output
        $TEST_CMD 2>&1 | tee test-output.txt
        TEST_EXIT_CODE=${PIPESTATUS[0]}
        
        echo "test_exit_code=$TEST_EXIT_CODE" >> $GITHUB_OUTPUT
        exit $TEST_EXIT_CODE

    - name: Parse test results
      id: parse-results
      if: always()
      shell: bash
      run: |
        # Parse Go test output
        PASSED=$(grep -c "^--- PASS:" test-output.txt 2>/dev/null || echo "0")
        FAILED=$(grep -c "^--- FAIL:" test-output.txt 2>/dev/null || echo "0")
        SKIPPED=$(grep -c "^--- SKIP:" test-output.txt 2>/dev/null || echo "0")
        
        echo "passed=$PASSED" >> $GITHUB_OUTPUT
        echo "failed=$FAILED" >> $GITHUB_OUTPUT
        echo "skipped=$SKIPPED" >> $GITHUB_OUTPUT
        
        # Extract failed test names
        FAILED_TESTS=$(grep "^--- FAIL:" test-output.txt 2>/dev/null | sed 's/--- FAIL: //' | sed 's/ (.*//' | tr '\n' ',' | sed 's/,$//' || echo "")
        
        # Create JSON results
        cat > test-results.json << EOF
        {
          "passed": $PASSED,
          "failed": $FAILED,
          "skipped": $SKIPPED,
          "failed_tests": "$FAILED_TESTS"
        }
        EOF
        
        echo "results=$(cat test-results.json | jq -c .)" >> $GITHUB_OUTPUT
        
        # Print summary
        echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Passed: $PASSED" >> $GITHUB_STEP_SUMMARY
        echo "- Failed: $FAILED" >> $GITHUB_STEP_SUMMARY
        echo "- Skipped: $SKIPPED" >> $GITHUB_STEP_SUMMARY
        if [ -n "$FAILED_TESTS" ]; then
          echo "### Failed Tests" >> $GITHUB_STEP_SUMMARY
          echo "$FAILED_TESTS" | tr ',' '\n' | while read test; do
            echo "- $test" >> $GITHUB_STEP_SUMMARY
          done
        fi

    - name: Upload test output
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: e2e-test-output
        path: |
          test-output.txt
          test-results.json
        retention-days: 7
