#!/usr/bin/env bash

set -o nounset
set -o errexit

cat << EOF
#
# DO NOT EDIT, generated by ./hack/gen-covignore.sh
#

# exclude the e2e suite and framework files
e2e/
test/
# exclude commands
cmd/
# exclude tools
tools/
# exclude examples
examples/
# log collectors cannot be unit tested as they need filesystem access
pkg/log_collector/
EOF

echo "# detected file coverage ignore"
grep -R '// IGNORE TEST COVERAGE' -ol monitors pkg | sort
