//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/awslabs/operatorpkg/status"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureState) DeepCopyInto(out *CaptureState) {
	*out = *in
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = new(CaptureStateRunning)
		(*in).DeepCopyInto(*out)
	}
	if in.Completed != nil {
		in, out := &in.Completed, &out.Completed
		*out = new(CaptureStateCompleted)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureState.
func (in *CaptureState) DeepCopy() *CaptureState {
	if in == nil {
		return nil
	}
	out := new(CaptureState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureStateCompleted) DeepCopyInto(out *CaptureStateCompleted) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.FinishedAt.DeepCopyInto(&out.FinishedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureStateCompleted.
func (in *CaptureStateCompleted) DeepCopy() *CaptureStateCompleted {
	if in == nil {
		return nil
	}
	out := new(CaptureStateCompleted)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureStateRunning) DeepCopyInto(out *CaptureStateRunning) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureStateRunning.
func (in *CaptureStateRunning) DeepCopy() *CaptureStateRunning {
	if in == nil {
		return nil
	}
	out := new(CaptureStateRunning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureStatus) DeepCopyInto(out *CaptureStatus) {
	*out = *in
	in.State.DeepCopyInto(&out.State)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureStatus.
func (in *CaptureStatus) DeepCopy() *CaptureStatus {
	if in == nil {
		return nil
	}
	out := new(CaptureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogCapture) DeepCopyInto(out *LogCapture) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]LogCategory, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogCapture.
func (in *LogCapture) DeepCopy() *LogCapture {
	if in == nil {
		return nil
	}
	out := new(LogCapture)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDiagnostic) DeepCopyInto(out *NodeDiagnostic) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDiagnostic.
func (in *NodeDiagnostic) DeepCopy() *NodeDiagnostic {
	if in == nil {
		return nil
	}
	out := new(NodeDiagnostic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeDiagnostic) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDiagnosticList) DeepCopyInto(out *NodeDiagnosticList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeDiagnostic, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDiagnosticList.
func (in *NodeDiagnosticList) DeepCopy() *NodeDiagnosticList {
	if in == nil {
		return nil
	}
	out := new(NodeDiagnosticList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeDiagnosticList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDiagnosticSpec) DeepCopyInto(out *NodeDiagnosticSpec) {
	*out = *in
	if in.LogCapture != nil {
		in, out := &in.LogCapture, &out.LogCapture
		*out = new(LogCapture)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDiagnosticSpec.
func (in *NodeDiagnosticSpec) DeepCopy() *NodeDiagnosticSpec {
	if in == nil {
		return nil
	}
	out := new(NodeDiagnosticSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDiagnosticStatus) DeepCopyInto(out *NodeDiagnosticStatus) {
	*out = *in
	if in.CaptureStatuses != nil {
		in, out := &in.CaptureStatuses, &out.CaptureStatuses
		*out = make([]CaptureStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]status.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDiagnosticStatus.
func (in *NodeDiagnosticStatus) DeepCopy() *NodeDiagnosticStatus {
	if in == nil {
		return nil
	}
	out := new(NodeDiagnosticStatus)
	in.DeepCopyInto(out)
	return out
}
