---
# create amazon-cloudwatch namespace
apiVersion: v1
kind: Namespace
metadata:
  name: amazon-cloudwatch
  labels:
    name: amazon-cloudwatch
---
# create cwagent service account and role binding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cwagent-prometheus
  namespace: amazon-cloudwatch
---
# create configmap for prometheus cwagent config
kind: ConfigMap
metadata:
  name: prometheus-cwagentconfig
  namespace: amazon-cloudwatch
apiVersion: v1
data:
  cwagentconfig.json: |
    {
      "agent": {
        "debug": true,
        "region": "{{.Region}}"
      },
      "logs": {
        "metrics_collected": {
          "prometheus": {
            "cluster_name": "{{.ClusterName}}",
            "log_group_name": "/aws/containerinsights/{{.ClusterName}}/prometheus",
            "prometheus_config_path": "/etc/prometheusconfig/prometheus.yaml",
            "emf_processor": {
              "metric_declaration": [
                {
                  "source_labels": ["job"],
                  "label_matcher": "eks-node-monitoring-agent-metrics",
                  "dimensions": [["job"]],
                  "metric_selectors": ["^.*$"]
                }
              ]
            }
          }
        },
        "force_flush_interval": 5
      }
    }
---
# create configmap for prometheus scrape config
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: amazon-cloudwatch
apiVersion: v1
data:
  prometheus.yaml: |
    global:
      scrape_interval: 30s
    scrape_configs:
    - job_name: 'eks-node-monitoring-agent-metrics'
      metrics_path: /metrics
      kubernetes_sd_configs:
      - role: pod
      static_configs:
      - targets: ["{{.MetricsHost}}"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cwagent-prometheus-role
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - nodes/proxy
    verbs: ["get", "list", "watch"]
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cwagent-prometheus-role-binding
subjects:
  - kind: ServiceAccount
    name: cwagent-prometheus
    namespace: amazon-cloudwatch
roleRef:
  kind: ClusterRole
  name: cwagent-prometheus-role
  apiGroup: rbac.authorization.k8s.io
