{{- if or .Values.nodeAgent.monitors .Values.nodeAgent.disabledEvents .Values.nodeAgent.eventThresholds }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eks-node-monitoring-agent.fullname" . }}-monitor-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eks-node-monitoring-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- with .Values.nodeAgent.disabledEvents }}
    disabledEvents:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nodeAgent.eventThresholds }}
    eventThresholds:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nodeAgent.monitors }}
    monitors:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
