name: Bot
run-name: 🤖 beep boop
on:
  issue_comment:
    types:
      - created
jobs:
  bot:
    if: ${{ github.repository == 'aws/eks-node-monitoring-agent' && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bot
